version: '3.8'
services:
  db:
    image: postgres:15
    container_name: rmcc_db
    environment:
      POSTGRES_USER: rolemaster
      POSTGRES_PASSWORD: mvp_password
      POSTGRES_DB: rolemaster_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: